package pojo;
// Generated Oct 14, 2022 1:53:41 AM by Hibernate Tools 4.3.1


import dao.DAOUser;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by Bayu & Arsyi
 */
public class User  implements java.io.Serializable {


     private int id;
     private String recordNo;
     private String nama;
     private Date tanggal;
     private int jumlahtiket;
     private String email;

    public User() {
    }

    public User(int id, String recordNo, String nama, Date tanggal, int jumlahtiket, String email) {
       this.id = id;
       this.recordNo = recordNo;
       this.nama = nama;
       this.tanggal = tanggal;
       this.jumlahtiket = jumlahtiket;
       this.email = email;
    }
   
    @Id @GeneratedValue(strategy = IDENTITY)  
    @Column(name = "id", unique = true, nullable = false)  
    public Integer getId()  
    {  
        return this.id;  
    }  
    public void setId(Integer id)  
    {  
        this.id = id;  
    }  
    @Column(name = "RecordNo", length = 20)  
    public String getRecordNo()  
    {  
        return this.recordNo;  
    }  
    public void setRecordNo(String recordNo)  
    {  
        this.recordNo = recordNo;  
    }  
    
    @Column(name = "Nama", length = 50) 
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    
    @Temporal(TemporalType.DATE)  
    @Column(name = "Tanggal", length = 10) 
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }
    
    @Column(name = "JumlahTiket") 
    public int getjumlahtiket() {
        return this.jumlahtiket;
    }
    
    public void setjumlahtiket(int jumlahtiket) {
        this.jumlahtiket = jumlahtiket;
    }
    
    @Column(name = "Email", length = 50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }


    public String addUser() {
        DAOUser user = new DAOUser();
        user.add(this);
        recordNo = "";
        nama = "";
        email = "";
        tanggal = getTanggal();
        jumlahtiket = 0;
        return "index";
    }
     public String updateUser() {
        DAOUser user = new DAOUser();
        user.update(this);
        recordNo = "";
        nama = "";
        email = "";
        tanggal = getTanggal();
        jumlahtiket = 0;
        return "search";
    }
      public String deleteUser() {
        DAOUser user = new DAOUser();
        user.delete(this);
        recordNo = "";
        nama = "";
        email = "";
        tanggal = getTanggal();
        jumlahtiket = 0;
        return "search";
      }
    
    //This method writes the values of contact object with System.out.println(user.toString()) code  
    @Override  
    public String toString()  
    {  
        return "user" +  
            "\n\t RecordNo: " + this.recordNo +  
            "\n\t Nama: " + this.nama +  
            "\n\t Tanggal: " + this.tanggal +  
            "\n\t Jumlah Tiket: " + this.jumlahtiket +    
            "\n\t Email: " + this.email;  
    } 
    
    
}


